version: '3'

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: docker_desafio_2_nginx
    networks:
      - node-mysql
    ports:
      - "8080:80"
    depends_on:
      - node
  node:
    build:
      context: ../node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-mysql
    tty: true
    container_name: docker_desafio_2_node
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: docker_desafio_2_db
    restart: always
    tty: true
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-mysql

networks:
  node-mysql:
    driver: bridge